# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donaldhomepage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='DonaldHomePage',
        ),
    ]
