# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='DonaldPage',
        ),
    ]
