# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('home', '0009_aboutelement_aboutmecontainer_aboutmepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmepage',
            name='aboutme_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
