# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('home', '0011_resumepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('company', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('details', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
