# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
