# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20161011_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumepage',
            name='body',
        ),
    ]
