# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='program',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
