# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20161011_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='author',
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='quote',
            field=models.CharField(max_length=511),
        ),
    ]
