# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='quote_container_object_list',
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
    ]
